---
resources:
   - name: source-code
     type: git
     icon: github
     source:
        uri: https://github.com/DipayanP007/Jenkins-Concourse-maven-project.git
        branch: master
        username: DipayanP007
        password: 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
   

jobs:
   - name: clean-test
     plan:
        - get: source-code
          trigger: true
        - task: maven-exec
          config:
             platform: linux
             image_resource:
                 type: docker-image
                 source:
                    repository: maven
             
             inputs:
                - name: source-code
             run:
                path: source-code/ci/script.sh

   - name: package-artifact
     build_log_retention:
        days: 2
        builds: 5
        minimum_succeeded_builds: 2
     plan:
          - get: source-code
            passed: [clean-test]
            trigger: true
          - task: package
            file: source-code/ci/task-package.yml
            

          - task: find-all
            config:
               platform: linux
               image_resource:
                  type: docker-image
                  source: {repository: openjdk}
               
               inputs:
                  - name: target

               caches:
                  - path: /root/.m2/
               run:
                  path: java
                  args:
                    - -jar 
                    - target/sample-application-for-jenkins-1.0-SNAPSHOT.jar